white-list-external:
  - localhost
  - kyma.local
black-list:
  - node_modules
black-list-internal: 
  - ./website/src/blog-posts/
timeout: 60
request-repeats: 5
basePath:
  - filePath: "./website/src/blog-posts/"
    prefix: "https://kyma-project.io"
    suffix: ""
files:
  - path: "./website/.github/ISSUE_TEMPLATE/security-vulnerability.md"
    config:
      white-list-internal: ["{CVSS"]
      white-list-external: ["https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N"]
  - path: ./website/docs/banner-modification.md
    config:
      white-list-internal:
        - ../src/banner/assets
  - path: ./website/docs/write-blog-posts.md
    config:
      white-list-external:
        - https://kyma-project.io/blog/some-address
      white-list-internal:
        - /docs/{VERSION}/root/kyma#overview-in-a-nutshell